//
// Generated file, do not edit! Created by opp_msgtool 6.0 from request.msg.
//

#ifndef __FATTREENEW_REQUEST_M_H
#define __FATTREENEW_REQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace fattreenew {

class Request;

}  // namespace fattreenew


namespace fattreenew {

// cplusplus {{
#include "Message.h"
// }}

/**
 * Class generated from <tt>request.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet Request
 * {
 *     char work_type;
 *     bool finished;
 *     bool ckp_launched;
 *     short port_index;
 *     short target_ost;
 *     uint32_t id;
 *     uint32_t master_id;
 *     uint32_t num_proc;
 *     uint32_t frag_size;
 *     uint64_t data_size;
 *     double proc_time;
 *     string src_addr;
 *     string des_addr;
 *     string master_id_addr;
 *     string next_hop_addr;
 *     string sendPath;
 *     string backPath;
 *     simtime_t generate_time;
 *     simtime_t arriveModule_time;
 *     simtime_t leaveModule_time;
 *     //omnetpp::cPacket pkg;
 * }
 * </pre>
 */
class Request : public ::omnetpp::cPacket
{
  protected:
    char work_type = 0;
    bool finished = false;
    bool ckp_launched = false;
    short port_index = 0;
    short target_ost = 0;
    uint32_t id = 0;
    uint32_t master_id = 0;
    uint32_t num_proc = 0;
    uint32_t frag_size = 0;
    uint64_t data_size = 0;
    double proc_time = 0;
    ::omnetpp::opp_string src_addr;
    ::omnetpp::opp_string des_addr;
    ::omnetpp::opp_string master_id_addr;
    ::omnetpp::opp_string next_hop_addr;
    ::omnetpp::opp_string sendPath;
    ::omnetpp::opp_string backPath;
    ::omnetpp::simtime_t generate_time = SIMTIME_ZERO;
    ::omnetpp::simtime_t arriveModule_time = SIMTIME_ZERO;
    ::omnetpp::simtime_t leaveModule_time = SIMTIME_ZERO;

  private:
    void copy(const Request& other);

  protected:
    bool operator==(const Request&) = delete;

  public:
    Request(const char *name=nullptr, short kind=0);
    Request(const Request& other);
    virtual ~Request();
    Request& operator=(const Request& other);
    virtual Request *dup() const override {return new Request(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual char getWork_type() const;
    virtual void setWork_type(char work_type);

    virtual bool getFinished() const;
    virtual void setFinished(bool finished);

    virtual bool getCkp_launched() const;
    virtual void setCkp_launched(bool ckp_launched);

    virtual short getPort_index() const;
    virtual void setPort_index(short port_index);

    virtual short getTarget_ost() const;
    virtual void setTarget_ost(short target_ost);

    virtual uint32_t getId() const;
    virtual void setId(uint32_t id);

    virtual uint32_t getMaster_id() const;
    virtual void setMaster_id(uint32_t master_id);

    virtual uint32_t getNum_proc() const;
    virtual void setNum_proc(uint32_t num_proc);

    virtual uint32_t getFrag_size() const;
    virtual void setFrag_size(uint32_t frag_size);

    virtual uint64_t getData_size() const;
    virtual void setData_size(uint64_t data_size);

    virtual double getProc_time() const;
    virtual void setProc_time(double proc_time);

    virtual const char * getSrc_addr() const;
    virtual void setSrc_addr(const char * src_addr);

    virtual const char * getDes_addr() const;
    virtual void setDes_addr(const char * des_addr);

    virtual const char * getMaster_id_addr() const;
    virtual void setMaster_id_addr(const char * master_id_addr);

    virtual const char * getNext_hop_addr() const;
    virtual void setNext_hop_addr(const char * next_hop_addr);

    virtual const char * getSendPath() const;
    virtual void setSendPath(const char * sendPath);

    virtual const char * getBackPath() const;
    virtual void setBackPath(const char * backPath);

    virtual ::omnetpp::simtime_t getGenerate_time() const;
    virtual void setGenerate_time(::omnetpp::simtime_t generate_time);

    virtual ::omnetpp::simtime_t getArriveModule_time() const;
    virtual void setArriveModule_time(::omnetpp::simtime_t arriveModule_time);

    virtual ::omnetpp::simtime_t getLeaveModule_time() const;
    virtual void setLeaveModule_time(::omnetpp::simtime_t leaveModule_time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Request& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Request& obj) {obj.parsimUnpack(b);}


}  // namespace fattreenew


namespace omnetpp {

template<> inline fattreenew::Request *fromAnyPtr(any_ptr ptr) { return check_and_cast<fattreenew::Request*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __FATTREENEW_REQUEST_M_H

